Add/servicelayer
saketverma-03/economy-bot-clanflare pull request #2
Opened 2024-01-18 19:18 UTC by SRV332003

2024-01-18 19:28 UTC, Teoriya commented on src/routes/oauth.ts
> +
```typescript
const tokenResponseData = await fetch(...)
const tokens = await tokenResponseData().json()
//send token in cookies
//return to the dashboard
```

2024-01-18 19:28 UTC, Teoriya commented on src/routes/oauth.ts
> +			// tokenResponseData.statusCode will be 401
even when handling error redirect to a something wrong happened page instead.

@saketverma-03 make a beautiful page.

2024-01-18 19:28 UTC, saketverma-03 requested changes

2024-01-18 19:28 UTC, saketverma-03 commented on src/routes/oauth.ts
> +			}).then((res) => res.json())
.json() will give authData to tokenResponseData

2024-01-18 19:28 UTC, saketverma-03 commented on src/routes/oauth.ts
> +        return tokenResponseData;
instead of returnign the token, do following steps
1. set tokens to cookies in response
2. redirect to Dashboard

2024-01-19 10:17 UTC, saketverma-03 approved these changes

2024-01-19 10:17 UTC, saketverma-03 commented on src/routes/oauth.ts
> +	if (code) {
```js
if(!code){
// throw some error
}
```

2024-01-19 10:17 UTC, merged